# Generated by Django 4.1 on 2022-10-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='attachments/'),
        ),
    ]
