# Generated by Django 4.1 on 2022-10-14 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xlsx', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
