# Generated by Django 4.1 on 2022-10-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_deleteduser_alter_post_posted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedUser',
        ),
    ]
