# Generated by Django 4.1 on 2022-10-24 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_deleteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='for_grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
